# Generated by Django 6.0 on 2025-12-10 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_year',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='productsensitive',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
