# Generated by Django 6.0 on 2025-12-10 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_release_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsensitive',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_sensitive_info', to='products.product'),
        ),
    ]
