# Generated by Django 6.0 on 2026-01-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productsensitive_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurposeCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='purpose_cat',
            field=models.ManyToManyField(max_length=100, related_name='products', to='products.purposecat'),
        ),
    ]
